name: Release
on: 
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: cook tofu
        uses: opentofu/setup-opentofu@v1
        with:
          terraform_version: 1.6.1

      - name: Lint
        run: docker run --rm -v "$(pwd):/data" -t ghcr.io/terraform-linters/tflint-bundle:latest

      - name: terraform fmt
        run: tofu fmt -check

      - name: Check tfdocs
        run: docker run --rm --volume "$(pwd):/terraform-docs" -u "$(id -u)" quay.io/terraform-docs/terraform-docs:latest /terraform-docs --output-check

