name: Release
on:
  workflow_dispatch:
  push:

jobs:
  tests:
    uses: 4s3ti/terraform-aws-cloudfront-and-edge/.github/workflows/tests.yml@main

  release:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: go-semantic-release/action@v1
        id: semrel
        name: Release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

